ubuntu 20.04 requires interface to be up before adding v6 default route

diff --git a/scripts/configure-container-network b/scripts/configure-container-network
--- a/scripts/configure-container-network
+++ b/scripts/configure-container-network
@@ -81,35 +81,39 @@ ip link show "${VETHCONTAINER}"
 ip link show "br-${INSTANCE}"
 
 # Move one end of the virtual ethernet cable inside the network namespace of the docker container
-ip link set ${VETHCONTAINER} netns ${INSTANCE} || {
+ip link set "${VETHCONTAINER}" netns "${INSTANCE}" || {
     echo "$0: FAILED to configure namespace, did ${CONTAINER} (pid ${DOCKERPID}) die?"
     exit 1
 }
-ip netns exec ${INSTANCE} ip link set ${VETHCONTAINER} name sarimner0
+ip netns exec "${INSTANCE}" ip link set "${VETHCONTAINER}" name sarimner0
 
 # Docker likes to disable IPv6
-ip netns exec ${INSTANCE} sysctl net.ipv6.conf.sarimner0.disable_ipv6=0
+ip netns exec "${INSTANCE}" sysctl net.ipv6.conf.sarimner0.disable_ipv6=0
 # DAD interferes with haproxy's first bind() of the IPv6 addresses,
 # and should really not be needed inside the namespace
-ip netns exec ${INSTANCE} sysctl net.ipv6.conf.sarimner0.accept_dad=0
+ip netns exec "${INSTANCE}" sysctl net.ipv6.conf.sarimner0.accept_dad=0
 # Allow bind to IP address before it is configured.
 # XXX Disabled since I can't decide if that would be a bug or a feature in this case.
 # ip netns exec ${INSTANCE} sysctl net.ipv4.ip_nonlocal_bind=1
 # ip netns exec ${INSTANCE} sysctl net.ipv6.ip_nonlocal_bind=1
 
-# Add IPv6 default gateway
-#sysctl net.ipv6.conf.${VETHHOST}.accept_dad=0
-v6gw=$(ip -6 addr list br-${INSTANCE} | awk '/inet6/{print $2}' | head -1 | awk -F / '{print $1}')
-if [[ $v6gw ]]; then
-    ip netns exec ${INSTANCE} ip -6 route add default via ${v6gw} dev sarimner0
-else
-    echo "Can't set up IPv6 routing from container, device ${VETHHOST} has no IPv6 address"
-fi
 
 # Add IP addresses to the network namespace of the docker container
-for IP in $(${SCRIPTSDIR}/frontend-config --instance ${INSTANCE} print_ips); do
-    ip netns exec ${INSTANCE} ip addr add ${IP} dev sarimner0
-    ip route add ${IP} dev br-${INSTANCE}
+for IP in $("${SCRIPTSDIR}"/frontend-config --instance "${INSTANCE}" print_ips); do
+    ip netns exec "${INSTANCE}" ip addr add "${IP}" dev sarimner0
+    ip route add "${IP}" dev br-"${INSTANCE}"
 done
 
-ip netns exec ${INSTANCE} ip link set sarimner0 up
+ip netns exec "${INSTANCE}" ip link set sarimner0 up
+
+
+# Set up IPv6 routing back out of the container, now that the interface is up.
+
+#sysctl net.ipv6.conf.${VETHHOST}.accept_dad=0
+v6gw=$(ip -6 addr list "br-${INSTANCE}" | awk '/inet6/{print $2}' | head -1 | awk -F / '{print $1}')
+if [[ $v6gw ]]; then
+    ip netns exec "${INSTANCE}" ip -6 route add default via "${v6gw}" dev sarimner0
+else
+    echo "$0: Can't set up IPv6 routing from container, device ${VETHHOST} has no IPv6 address"
+fi
+
